quarkus:
  http:
    cors:
      # ðŸ”“ activar el filtro CORS
      enabled: true

      # OrÃ­genes permitidos (tu frontend)
      origins: "http://localhost:5173"

      # MÃ©todos permitidos
      methods: "GET,PUT,POST,DELETE,OPTIONS"

      # Headers permitidos desde el front
      headers: "origin,accept,authorization,content-type,x-requested-with"

      # Headers expuestos al front (opcional)
      exposed-headers: "Access-Control-Allow-Origin,Authorization,Content-Disposition"

      # Tiempo que el navegador puede cachear el preflight
      access-control-max-age: "24H"

      # Permitir credenciales (cookies, auth, etc.)
      access-control-allow-credentials: true

geolite2:
  city-db: "geo/GeoLite2-City.mmdb"